### ISSUE TITLE
Spec changes incomplete

### ISSUE THREAD

**Issue by gbracha** [sigmundch/DEP-nonuri-imports#2]
The spec changes address syntax but not semantics. Somewhere, the mapping from import qualifiedIdentifier to existing imports needs to be defined.

**Comment by lrhn** [comment]
Could probably be handled by defining equivalences.
`import <identifier> <modifiers>;` is equivalent to `import "package:<identifier>/<identifier>.dart <modifiers>;`, etc.

**Comment by sigmundch** [comment]
Added changes here:
https://github.com/sigmundch/DEP-nonuri-imports/blob/b84731fade876cadbcce2626151fb6902f7a8980/proposal.md#spec-changes

I noticed that we could also move all this sugaring as part of the definition of URI itself in section **18.5** of the spec, I explain that idea here:
https://github.com/sigmundch/DEP-nonuri-imports/blob/b84731fade876cadbcce2626151fb6902f7a8980/proposal.md#alternative-spec-modification
